### ISSUE TITLE
Change repo name

### ISSUE THREAD

**Issue by lovesegfault** [RustAudio/simplemad#26]
I think it should be `simple-map-rs` or `simplemap-rs`; what do you think @bendykst?

**Comment by bendykst** [comment]
I would be open to that. It's kind of an eyesore, isn't it? How about just simplemad? @est31?

**Comment by lovesegfault** [comment]
That sounds good to me too :)

I'll make a PR with the yakshaving

**Comment by est31** [comment]
Yeah simplemad sounds good. :+1:

**Comment by est31** [comment]
It's been changed to simplemad. Awaiting a PR that does the yakshaving :)

**Comment by est31** [comment]
Resolved by the rename and #29
